@startuml
skinparam linestyle ortho
hide empty members

rectangle " " as source #line:transparent;text:transparent

rectangle ":ControladorPedidos" as cp
collections ":Hogar" as hs
rectangle "h:Hogar" as h
rectangle "p:Pedido" as p

source-right-> cp: 1: registrarPedido(habitante, direccion, coordenadas)

cp -down-> hs: 1.1: h:=seleccionar(habitante, direccion)

cp -right-> h: 1.2: [no existe]\ncrear(habitante, direccion)

cp -down-> hs: 1.3: [no existe]\nagregar(h)

cp -up-> p: 2: crear(fecha_actual(), coordenadas, h, "En espera")

@enduml