@startuml
left to right direction

:Habitante:
:Recolector:
:API de Geolocalización: as api
:Coordinador de ruta: as coordinador

package Sistema {
  usecase "Ingresar solicitud de retiro" as UC1
  usecase "Validar ubicación automáticamente" as UC2
  usecase "Ingresar o modificar datos personales" as UC3
  usecase "Ver estado de solicitud de retiro" as UC4
  usecase "Operar ruta asignada" as UC5
  usecase "Visualizar ruta en un mapa" as UC6
  usecase "Reportar resultado de retiro" as UC7
  usecase "Emitir comprobante" as UC8
	usecase "Agregar solicitud a zona de recolección" as UC9
	usecase "Asignar ruta generada a recolector disponible" as UC10
	usecase "Visualizar rutas en un mapa" as UC11
}

:UC1: --> :UC2: : <<include>>
:UC5: --> :UC6: : <<include>
:UC5: --> :UC7: : <<include>>
:UC7: --> :UC8: : <<include>>
:UC2: --> :UC9: : <<extend>>
:UC10: --> :UC11: : <<include>>

:Habitante: -- UC1
:Habitante: -- UC3
:Habitante: -- UC4
:Recolector: -- UC5
:api: -- UC2
:coordinador: -- UC10
@enduml
