@startuml
left to right direction

:Habitante:
:Recolector:
:API de Geolocalización: as api

package Sistema {
  usecase "Ingresar solicitud de retiro." as UC1
  usecase "Confirmar ubicación (automáticamente o manualmente) y emitir solicitud." as UC2
  usecase "Ingresar datos personales: nombre, dirección, teléfono." as UC3
  usecase "Modificar datos." as UC4
  usecase "Ver estado de solicitud de retiro." as UC5
  usecase "Seleccionar 1 o más retiros para cumplir." as UC6
  usecase "Visualizar retiros disponibles cercanos en un mapa." as UC7
  usecase "Reportar completación de retiro." as UC8
  usecase "Visualizar rutas de recolecciones." as UC9
  usecase "Notificar habitante de la completación de su pedido." as UC10
}

:UC1: --> :UC2: : <<include>>
:UC1: --> :UC3: : <<include>>
:UC6: --> :UC7: : <<include>
:UC9: --> :UC6: : <<include>>
:UC8: --> :UC6: : <<include>>
:UC8: --> :UC10: : <<include>>


:UC4: --> :UC3:: <<extend>>
:UC5: --> :UC1:: <<extend>>



:Habitante: -- UC1
:Habitante: -- UC3
:Recolector: -- UC6
:Recolector: -- UC7
:Recolector: -- UC8
:Recolector: -- UC9
:api: -- UC2
@enduml
